stages:
    - test
    - deploy

test 7.1 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.1
    stage: test
    script:
        - ./tests.sh composer_update_prefer_lowest
        - ./tests.sh phpunit
        - ./tests.sh phpmd
    artifacts:
        paths:
            - phpmd.html
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.1 latest:
    image: registry.gitlab.com/anezi/php-dev:7.1
    stage: test
    script:
        - ./tests.sh composer_update_prefer_latest
        - ./tests.sh phpunit_with_coverage
    artifacts:
        paths:
            - coverage
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.2
    stage: test
    script:
        - ./tests.sh composer_update_prefer_lowest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2 latest:
    image: registry.gitlab.com/anezi/php-dev:7.2
    stage: test
    script:
        - ./tests.sh composer_update_prefer_latest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.3 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.3
    stage: test
    script:
        - ./tests.sh composer_update_prefer_lowest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.3 latest:
    image: registry.gitlab.com/anezi/php-dev:7.3
    stage: test
    script:
        - ./tests.sh composer_update_prefer_latest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

pages:
    image: alpine:latest
    stage: deploy
    script:
        - mkdir public
        - mv coverage public/
        - echo "Visit https://anezi.gitlab.io/email-validator/coverage/ to verify the results."
        - mv phpmd.html public/
        - echo "Visit https://anezi.gitlab.io/email-validator/phpmd.html to verify the results."
    artifacts:
        paths:
            - public
    only:
        - master
