stages:
    - test
    - deploy

test 7.1 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.1
    stage: test
    script:
        - ./tests.sh composer_update_prefer_lowest
        - ./tests.sh phpunit
        - ./tests.sh phpmd
    artifacts:
        paths:
            - phpmd.html
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.1 latest:
    image: registry.gitlab.com/anezi/php-dev:7.1
    stage: test
    script:
        - ./tests.sh composer_update_prefer_latest
        - ./tests.sh phpunit_with_coverage
    artifacts:
        paths:
            - coverage
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.2
    stage: test
    script:
        - ./tests.sh composer_update_prefer_lowest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.2 latest:
    image: registry.gitlab.com/anezi/php-dev:7.2
    stage: test
    script:
        - ./tests.sh composer_update_prefer_latest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.3 lowest:
    image: registry.gitlab.com/anezi/php-dev:7.3
    stage: test
    script:
        - ./tests.sh composer_update_prefer_lowest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

test 7.3 latest:
    image: registry.gitlab.com/anezi/php-dev:7.3
    stage: test
    script:
        - ./tests.sh composer_update_prefer_latest
        - ./tests.sh phpunit
    cache:
        key: "$CI_JOB_NAME"
        untracked: true

pages:
    image: alpine:latest
    stage: deploy
    script:
        - mkdir public
        - mv coverage public/
        - mv phpmd.html public/
        - echo "Visit https://packages.pages.gitlab.com/locale to verify the results."
    artifacts:
        paths:
            - public
    only:
        - master

#trigger_build:
#    image: registry.gitlab.com/images/curl
#    stage: deploy
#    variables:
#        PROJECT: "packages/list"
#        REF: "master"
#        TOKEN: "e797ae6146398ae510ef0ea9169dc2"
#    script:
#        - PROJECT=`echo $PROJECT | sed -e "s/\//%2F/g"`
#        - curl -X POST -F token=$TOKEN -F ref=$REF https://git.gitlab.com/api/v4/projects/$PROJECT/trigger/pipeline
#    only:
#        - tags
